/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupProfileRouteImport } from './routes/setup-profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiMlRouteImport } from './routes/api/ml'
import { Route as ApiKwsWebhookRouteImport } from './routes/api/kws-webhook'
import { Route as ApiKwsVerificationRouteImport } from './routes/api/kws-verification'
import { Route as AuthedWriteRouteImport } from './routes/_authed/write'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedMessagesRouteImport } from './routes/_authed/messages'
import { Route as AuthedJobsRouteImport } from './routes/_authed/jobs'
import { Route as AuthedFeedRouteImport } from './routes/_authed/feed'
import { Route as AuthedBusinessRouteImport } from './routes/_authed/business'
import { Route as AuthedBookmarksRouteImport } from './routes/_authed/bookmarks'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as ApiSseChannelRouteImport } from './routes/api/sse.$channel'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsPrivacyRouteImport } from './routes/_authed/settings/privacy'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed/settings/notifications'
import { Route as AuthedSettingsMutedRouteImport } from './routes/_authed/settings/muted'
import { Route as AuthedSettingsAiRouteImport } from './routes/_authed/settings/ai'
import { Route as AuthedSettingsAccountRouteImport } from './routes/_authed/settings/account'
import { Route as AuthedMessagesIdRouteImport } from './routes/_authed/messages.$id'
import { Route as AuthedBusinessNewRouteImport } from './routes/_authed/business_.new'
import { Route as AuthedPostPostIdAnalyticsRouteImport } from './routes/_authed/post.$postId.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/setup-profile',
  path: '/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlRoute = ApiMlRouteImport.update({
  id: '/api/ml',
  path: '/api/ml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKwsWebhookRoute = ApiKwsWebhookRouteImport.update({
  id: '/api/kws-webhook',
  path: '/api/kws-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKwsVerificationRoute = ApiKwsVerificationRouteImport.update({
  id: '/api/kws-verification',
  path: '/api/kws-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWriteRoute = AuthedWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesRoute = AuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRoute = AuthedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedRoute = AuthedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBusinessRoute = AuthedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookmarksRoute = AuthedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const ApiSseChannelRoute = ApiSseChannelRouteImport.update({
  id: '/api/sse/$channel',
  path: '/api/sse/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsPrivacyRoute = AuthedSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMutedRoute = AuthedSettingsMutedRouteImport.update({
  id: '/muted',
  path: '/muted',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAiRoute = AuthedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAccountRoute = AuthedSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedMessagesIdRoute = AuthedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedMessagesRoute,
} as any)
const AuthedBusinessNewRoute = AuthedBusinessNewRouteImport.update({
  id: '/business_/new',
  path: '/business/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostPostIdAnalyticsRoute =
  AuthedPostPostIdAnalyticsRouteImport.update({
    id: '/post/$postId/analytics',
    path: '/post/$postId/analytics',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/setup-profile': typeof SetupProfileRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/bookmarks': typeof AuthedBookmarksRoute
  '/business': typeof AuthedBusinessRoute
  '/feed': typeof AuthedFeedRoute
  '/jobs': typeof AuthedJobsRoute
  '/messages': typeof AuthedMessagesRouteWithChildren
  '/notifications': typeof AuthedNotificationsRoute
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/write': typeof AuthedWriteRoute
  '/api/kws-verification': typeof ApiKwsVerificationRoute
  '/api/kws-webhook': typeof ApiKwsWebhookRoute
  '/api/ml': typeof ApiMlRoute
  '/api/upload': typeof ApiUploadRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/business/new': typeof AuthedBusinessNewRoute
  '/messages/$id': typeof AuthedMessagesIdRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/ai': typeof AuthedSettingsAiRoute
  '/settings/muted': typeof AuthedSettingsMutedRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sse/$channel': typeof ApiSseChannelRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/post/$postId/analytics': typeof AuthedPostPostIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/setup-profile': typeof SetupProfileRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/bookmarks': typeof AuthedBookmarksRoute
  '/business': typeof AuthedBusinessRoute
  '/feed': typeof AuthedFeedRoute
  '/jobs': typeof AuthedJobsRoute
  '/messages': typeof AuthedMessagesRouteWithChildren
  '/notifications': typeof AuthedNotificationsRoute
  '/search': typeof AuthedSearchRoute
  '/write': typeof AuthedWriteRoute
  '/api/kws-verification': typeof ApiKwsVerificationRoute
  '/api/kws-webhook': typeof ApiKwsWebhookRoute
  '/api/ml': typeof ApiMlRoute
  '/api/upload': typeof ApiUploadRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/business/new': typeof AuthedBusinessNewRoute
  '/messages/$id': typeof AuthedMessagesIdRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/ai': typeof AuthedSettingsAiRoute
  '/settings/muted': typeof AuthedSettingsMutedRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sse/$channel': typeof ApiSseChannelRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/post/$postId/analytics': typeof AuthedPostPostIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/setup-profile': typeof SetupProfileRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/_authed/bookmarks': typeof AuthedBookmarksRoute
  '/_authed/business': typeof AuthedBusinessRoute
  '/_authed/feed': typeof AuthedFeedRoute
  '/_authed/jobs': typeof AuthedJobsRoute
  '/_authed/messages': typeof AuthedMessagesRouteWithChildren
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/write': typeof AuthedWriteRoute
  '/api/kws-verification': typeof ApiKwsVerificationRoute
  '/api/kws-webhook': typeof ApiKwsWebhookRoute
  '/api/ml': typeof ApiMlRoute
  '/api/upload': typeof ApiUploadRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/_authed/business_/new': typeof AuthedBusinessNewRoute
  '/_authed/messages/$id': typeof AuthedMessagesIdRoute
  '/_authed/settings/account': typeof AuthedSettingsAccountRoute
  '/_authed/settings/ai': typeof AuthedSettingsAiRoute
  '/_authed/settings/muted': typeof AuthedSettingsMutedRoute
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sse/$channel': typeof ApiSseChannelRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/post/$postId/analytics': typeof AuthedPostPostIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/setup-profile'
    | '/sign-in'
    | '/terms'
    | '/bookmarks'
    | '/business'
    | '/feed'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/write'
    | '/api/kws-verification'
    | '/api/kws-webhook'
    | '/api/ml'
    | '/api/upload'
    | '/article/$slug'
    | '/company/$slug'
    | '/post/$postId'
    | '/profile/$handle'
    | '/business/new'
    | '/messages/$id'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/muted'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/api/auth/$'
    | '/api/sse/$channel'
    | '/settings/'
    | '/post/$postId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/setup-profile'
    | '/sign-in'
    | '/terms'
    | '/bookmarks'
    | '/business'
    | '/feed'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/write'
    | '/api/kws-verification'
    | '/api/kws-webhook'
    | '/api/ml'
    | '/api/upload'
    | '/article/$slug'
    | '/company/$slug'
    | '/post/$postId'
    | '/profile/$handle'
    | '/business/new'
    | '/messages/$id'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/muted'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/api/auth/$'
    | '/api/sse/$channel'
    | '/settings'
    | '/post/$postId/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/privacy'
    | '/setup-profile'
    | '/sign-in'
    | '/terms'
    | '/_authed/bookmarks'
    | '/_authed/business'
    | '/_authed/feed'
    | '/_authed/jobs'
    | '/_authed/messages'
    | '/_authed/notifications'
    | '/_authed/search'
    | '/_authed/settings'
    | '/_authed/write'
    | '/api/kws-verification'
    | '/api/kws-webhook'
    | '/api/ml'
    | '/api/upload'
    | '/article/$slug'
    | '/company/$slug'
    | '/post/$postId'
    | '/profile/$handle'
    | '/_authed/business_/new'
    | '/_authed/messages/$id'
    | '/_authed/settings/account'
    | '/_authed/settings/ai'
    | '/_authed/settings/muted'
    | '/_authed/settings/notifications'
    | '/_authed/settings/privacy'
    | '/api/auth/$'
    | '/api/sse/$channel'
    | '/_authed/settings/'
    | '/_authed/post/$postId/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SetupProfileRoute: typeof SetupProfileRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  ApiKwsVerificationRoute: typeof ApiKwsVerificationRoute
  ApiKwsWebhookRoute: typeof ApiKwsWebhookRoute
  ApiMlRoute: typeof ApiMlRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CompanySlugRoute: typeof CompanySlugRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSseChannelRoute: typeof ApiSseChannelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-profile': {
      id: '/setup-profile'
      path: '/setup-profile'
      fullPath: '/setup-profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml': {
      id: '/api/ml'
      path: '/api/ml'
      fullPath: '/api/ml'
      preLoaderRoute: typeof ApiMlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kws-webhook': {
      id: '/api/kws-webhook'
      path: '/api/kws-webhook'
      fullPath: '/api/kws-webhook'
      preLoaderRoute: typeof ApiKwsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kws-verification': {
      id: '/api/kws-verification'
      path: '/api/kws-verification'
      fullPath: '/api/kws-verification'
      preLoaderRoute: typeof ApiKwsVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/write': {
      id: '/_authed/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof AuthedWriteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages': {
      id: '/_authed/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthedMessagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs': {
      id: '/_authed/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feed': {
      id: '/_authed/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthedFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/business': {
      id: '/_authed/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthedBusinessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookmarks': {
      id: '/_authed/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthedBookmarksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/api/sse/$channel': {
      id: '/api/sse/$channel'
      path: '/api/sse/$channel'
      fullPath: '/api/sse/$channel'
      preLoaderRoute: typeof ApiSseChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/privacy': {
      id: '/_authed/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthedSettingsPrivacyRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/muted': {
      id: '/_authed/settings/muted'
      path: '/muted'
      fullPath: '/settings/muted'
      preLoaderRoute: typeof AuthedSettingsMutedRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/ai': {
      id: '/_authed/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthedSettingsAiRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/account': {
      id: '/_authed/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthedSettingsAccountRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/messages/$id': {
      id: '/_authed/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthedMessagesIdRouteImport
      parentRoute: typeof AuthedMessagesRoute
    }
    '/_authed/business_/new': {
      id: '/_authed/business_/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof AuthedBusinessNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/post/$postId/analytics': {
      id: '/_authed/post/$postId/analytics'
      path: '/post/$postId/analytics'
      fullPath: '/post/$postId/analytics'
      preLoaderRoute: typeof AuthedPostPostIdAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedMessagesRouteChildren {
  AuthedMessagesIdRoute: typeof AuthedMessagesIdRoute
}

const AuthedMessagesRouteChildren: AuthedMessagesRouteChildren = {
  AuthedMessagesIdRoute: AuthedMessagesIdRoute,
}

const AuthedMessagesRouteWithChildren = AuthedMessagesRoute._addFileChildren(
  AuthedMessagesRouteChildren,
)

interface AuthedSettingsRouteChildren {
  AuthedSettingsAccountRoute: typeof AuthedSettingsAccountRoute
  AuthedSettingsAiRoute: typeof AuthedSettingsAiRoute
  AuthedSettingsMutedRoute: typeof AuthedSettingsMutedRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsPrivacyRoute: typeof AuthedSettingsPrivacyRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAccountRoute: AuthedSettingsAccountRoute,
  AuthedSettingsAiRoute: AuthedSettingsAiRoute,
  AuthedSettingsMutedRoute: AuthedSettingsMutedRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsPrivacyRoute: AuthedSettingsPrivacyRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedBookmarksRoute: typeof AuthedBookmarksRoute
  AuthedBusinessRoute: typeof AuthedBusinessRoute
  AuthedFeedRoute: typeof AuthedFeedRoute
  AuthedJobsRoute: typeof AuthedJobsRoute
  AuthedMessagesRoute: typeof AuthedMessagesRouteWithChildren
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedWriteRoute: typeof AuthedWriteRoute
  AuthedBusinessNewRoute: typeof AuthedBusinessNewRoute
  AuthedPostPostIdAnalyticsRoute: typeof AuthedPostPostIdAnalyticsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBookmarksRoute: AuthedBookmarksRoute,
  AuthedBusinessRoute: AuthedBusinessRoute,
  AuthedFeedRoute: AuthedFeedRoute,
  AuthedJobsRoute: AuthedJobsRoute,
  AuthedMessagesRoute: AuthedMessagesRouteWithChildren,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedWriteRoute: AuthedWriteRoute,
  AuthedBusinessNewRoute: AuthedBusinessNewRoute,
  AuthedPostPostIdAnalyticsRoute: AuthedPostPostIdAnalyticsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SetupProfileRoute: SetupProfileRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  ApiKwsVerificationRoute: ApiKwsVerificationRoute,
  ApiKwsWebhookRoute: ApiKwsWebhookRoute,
  ApiMlRoute: ApiMlRoute,
  ApiUploadRoute: ApiUploadRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CompanySlugRoute: CompanySlugRoute,
  PostPostIdRoute: PostPostIdRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSseChannelRoute: ApiSseChannelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
